name: no_todo_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  app_tracking_transparency: ^2.0.2+1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  drift: ^1.4.0
  flutter_riverpod: ^1.0.3
  flutter_screenutil: ^5.3.1
  google_mobile_ads: ^1.1.0
  intl: ^0.17.0
  json_serializable: ^6.1.5
  path: ^1.8.0
  path_provider: ^2.0.9
  shared_preferences: ^2.0.13
  sqlite3_flutter_libs: ^0.5.4

dev_dependencies:
  build_runner: ^2.1.7
  drift_dev: ^1.4.0
  flutter_launcher_icons: ^0.9.2
  flutter_lints:
  flutter_native_splash: ^2.1.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#ff5252"
  adaptive_icon_foreground: "assets/images/icon.png"

flutter_native_splash:
  color: "#ff5252"
  image: "assets/images/splash.png"
